### PR TITLE
Include the git SHA1 short hash as part of the USB device serial number

### PR DESCRIPTION
**Pull request by bschwind**
From #20

### CODE REVIEW

**Review by strohel — APPROVED** [review]
Looks good. As an alternative for doing it ad-hoc, we might have used `vergen` or `built`, but probably you didn't want to introduce a dependency?

It would also be a bit more natural for me to pass just the git hash from the build script and prepend the `tonari-panel-controller-` in the actual binary, but that's a small nit.

**Comment by bschwind** [comment]
> As an alternative for doing it ad-hoc, we might have used vergen or built, but probably you didn't want to introduce a dependency?

Yep, I specifically didn't want to add any dependencies as it's somewhat annoying in a `no_std` context.

> It would also be a bit more natural for me to pass just the git hash from the build script

I would have done the same, but I wanted to avoid dynamic allocation in the firmware. I suppose since I know the slice length I could make it work but I'm not 100% sure how straightforward the code would be with that.

**Comment by bschwind** [comment]
(Sorry I'm just merging these without reviews, I'm testing these directly on the hardware currently)

**Comment by strohel** [comment]
Ad. question: I see, got it.

Merging quickly is cool, the comments wouldn't have resulted in any changes.

**Pull request merged**
